test_that("Running EFM", {
  outpath = tempdir()
  input = test_path("testdata", "Sample01a_set1.tsv")
  inputb = test_path("testdata", "Sample01b_rep_set1.tsv")
  alla = test_path("testdata", "Sample01a_snpsetscombined_evidence.tsv")
  allb = test_path("testdata", "Sample01b_snpsetscombined_evidence.tsv")
  kin_a = test_path("testdata", "Sample01a_Sample_Report_2021_11_01_16_56_38.xlsx")
  kin_b = test_path("testdata", "Sample01b_Sample_Report_2021_12_09_14_51_19.xlsx")
  file.copy(c(input, inputb, alla, allb, kin_a, kin_b), outpath)
  popFreq = mixder::popFreq_1000G
  refData = euroformix::sample_tableToList(euroformix::tableReader(test_path("testdata", "EFM_references.csv")))
  attable_a = process_kinreport("Sample01a", "", outpath, 0.015, 10)
  attable_b = process_kinreport("Sample01a", "Sample01b", outpath, 0.015, 10)
  expect_message(run_efm(popFreq, refData, "Sample01a", "", outpath, glue("{outpath}/output"), attable_a, 1, cond = NULL, uncond=FALSE), "Processing set #1<br/>")
  expect_message(run_efm(popFreq, refData, "Sample01a", "", outpath, glue("{outpath}/output"), attable_a, 1, cond = NULL, uncond=TRUE), "Running unconditioned analysis<br/>")
  expect_message(run_efm(popFreq, refData, "Sample01a", "", outpath, glue("{outpath}/output"), attable_a, 1, cond = c("Ref1"), uncond=FALSE), "Running conditioned analysis on Ref1<br/>")
  expect_message(run_efm(popFreq, refData, "Sample01a", "", outpath, glue("{outpath}/output"), attable_a, 1, cond = c("Ref2"), uncond=FALSE), "Running conditioned analysis on Ref2<br/>")
  expect_message(run_efm(popFreq, refData, "Sample01a", "Sample01b", outpath, glue("{outpath}/output"), attable_b, 1, cond = NULL, uncond=FALSE), "Processing set #1<br/>")
  expect_message(run_efm(mixder::popFreq, refData, "Sample01a", "Sample01b", outpath, glue("{outpath}/output"), attable_b, 1, cond = NULL, uncond=FALSE), "Processing set #1<br/>")
})
