test_that("Run MixDeR Report", {
  tmpdir = tempdir()
  file.copy(test_path("testdata", "Sample01a_Sample_Report_2021_11_01_16_56_38.xlsx"), tmpdir)
  outpath = paste0(tempdir(), "/snp_sets/output/Single/GEDMatchPROReports")
  run_mixder_report(sample_manifest=test_path("testdata", "samplemanifest_01a.txt"), sample_reports=tmpdir, output="output")
  exp_report = read.csv(test_path("testdata", "Sample01a_uncond_major_Single_GEDmatchPROReport.txt"), header=T, sep="\t")
  obs_report = read.csv(glue("{outpath}/Sample01a_uncond_major_Single_GEDmatchPROReport.txt"), header=T, sep="\t")
  expect_equal(exp_report, obs_report)
  refdir=paste0(tmpdir, "/ref")
  dir.create(refdir)
  file.copy(test_path("testdata", "EFM_references.csv"), refdir)
  exp_cond_report = read.csv(test_path("testdata", "Sample01a_major_contrib_conditioned_on_Ref2_Single_GEDmatchPROReport.txt"), header=T, sep="\t")
  run_mixder_report(sample_manifest=test_path("testdata", "samplemanifest_01a.txt"), sample_reports=tmpdir, output="output", cond=TRUE, uncond=FALSE, refpath=refdir, refs=list("Ref2"))
  list.files(outpath)
  obs_cond_report = read.csv(glue("{outpath}/Sample01a_major_contrib_conditioned_on_Ref2_Single_GEDmatchPROReport.txt"), header=T, sep="\t")
  expect_equal(exp_cond_report, obs_cond_report)
})
