test_that("Run MixDeR Metrics", {
  tmpdir = tempdir()
  file.copy(test_path("testdata", "Sample01a_Sample_Report_2021_11_01_16_56_38.xlsx"), tmpdir)
  outpath = paste0(tempdir(), "/snp_sets/output/Single/Sample01a/")
  refdir=paste0(tmpdir, "/ref")
  dir.create(refdir)
  file.copy(test_path("testdata", "EFM_references.csv"), refdir)
  run_mixder_metrics(sample_manifest=test_path("testdata", "samplemanifest_01a.txt"), sample_reports=tmpdir, output="output", refpath=refdir, major="Ref1", minor="Ref2")
  exp_metrics = read.csv(test_path("testdata", "Ref1_uncond_metrics_table.tsv"), header=T, sep="\t")
  obs_metrics = read.csv(glue("{outpath}/unconditioned/Ref1_metrics_table.tsv"), header=T, sep="\t")
  expect_equal(exp_metrics, obs_metrics)
  exp_cond_metrics = read.csv(test_path("testdata", "Ref1_cond_metrics_table.tsv"), header=T, sep="\t")
  run_mixder_metrics(sample="Sample01a", sample_reports=tmpdir, output="output", refpath=refdir, refs=list("Ref2"), major="Ref1", minor="Ref2")
  obs_cond_metrics = read.csv(glue("{outpath}/conditioned/Ref1_metrics_table.tsv"), header=T, sep="\t")
  expect_equal(exp_cond_metrics, obs_cond_metrics)
})
